plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'team5'
version = 'unspecified'

repositories {
    mavenCentral()
}

java {
    modularity.inferModulePath = false
}

dependencies {
    implementation project(':controller')
    implementation project(':core')

    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

javafx {
    version = '21'
    modules = ['javafx.controls', 'javafx.fxml']
}

test {
    useJUnitPlatform()
}

application {
    mainClass = 'Main'
}
